services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: VynPay
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks removida - vai usar rede padrão

  # app:
  #   build: .
  #   container_name: auth_app
  #   depends_on:
  #     - postgres
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/AuthAssistencia
  #     SPRING_DATASOURCE_USERNAME: admin
  #     SPRING_DATASOURCE_PASSWORD: admin123
  #   ports:
  #     - "8080:8080"
  #   networks removida

volumes:
  postgres_data:

# networks seção removida completamente